version: 2

sources:
  - name: db1
    database: db1
    schema: db1
    # freshness:
      #   warn_after: {count: 12, period: hour}
      #   error_after: {count: 24, period: hour}
      # loaded_at_field: created_at
    loader: S3
    description: "External tables"

    tables:

      - name: customer
        identifier: src_customer
        columns:
          - name: c_custkey
            description: ""
          - name: c_name
            description: ""
          - name: c_address
            description: ""
          - name: c_city
            description: ""
          - name: c_nation
            description: ""
          - name: c_region
            description: ""
          - name: c_phone
            description: ""
          - name: c_mktsegment
            description: ""

      - name: lineorder
        identifier: src_lineorder
        columns:
          - name: lo_orderkey
            description: ""
          - name: lo_linenumber
            description: ""
          - name: lo_custkey
            description: ""
          - name: lo_partkey
            description: ""
          - name: lo_suppkey
            description: ""
          - name: lo_orderdate
            description: ""
          - name: lo_orderpriority
            description: ""
          - name: lo_shippriority
            description: ""
          - name: lo_quantity
            description: ""
          - name: lo_extendedprice
            description: ""
          - name: lo_ordtotalprice
            description: ""
          - name: lo_discount
            description: ""
          - name: lo_revenue
            description: ""
          - name: lo_supplycost
            description: ""
          - name: lo_tax
            description: ""
          - name: lo_commitdate
            description: ""
          - name: lo_shipmode
            description: ""

      - name: part
        identifier: src_part
        columns:
          - name: p_partkey
            description: ""
          - name: p_name
            description: ""
          - name: p_mfgr
            description: ""
          - name: p_category
            description: ""
          - name: p_brand
            description: ""
          - name: p_color
            description: ""
          - name: p_type
            description: ""
          - name: p_size
            description: ""
          - name: p_container
            description: ""

      - name: supplier
        identifier: src_supplier
        columns:
          - name: s_suppkey
            description: ""
          - name: s_name
            description: ""
          - name: s_address
            description: ""
          - name: s_city
            description: ""
          - name: s_nation
            description: ""
          - name: s_region
            description: ""
          - name: s_phone
            description: ""
